# Generated by Django 3.2.6 on 2021-08-06 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('hash', models.CharField(db_index=True, max_length=64, primary_key=True, serialize=False)),
                ('version', models.IntegerField()),
                ('height', models.IntegerField(db_index=True)),
                ('prev_root', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('output_root', models.CharField(max_length=64)),
                ('range_proof_root', models.CharField(max_length=64)),
                ('kernel_root', models.CharField(max_length=64)),
                ('nonce', models.TextField()),
                ('edge_bits', models.IntegerField()),
                ('total_difficulty', models.BigIntegerField()),
                ('secondary_scaling', models.IntegerField()),
                ('total_kernel_offset', models.CharField(max_length=64)),
                ('output_mmr_size', models.IntegerField()),
                ('kernel_mmr_size', models.IntegerField()),
                ('previous', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children_set', to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_type', models.TextField(choices=[('Transaction', 'Transaction'), ('Coinbase', 'Coinbase')])),
                ('commit', models.CharField(db_index=True, max_length=66)),
                ('spent', models.BooleanField()),
                ('proof', models.TextField(null=True)),
                ('proof_hash', models.CharField(max_length=64)),
                ('block_height', models.IntegerField(null=True)),
                ('merkle_proof', models.TextField(null=True)),
                ('mmr_index', models.IntegerField(null=True)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='Kernel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('features', models.TextField()),
                ('fee', models.IntegerField()),
                ('fee_shift', models.IntegerField()),
                ('lock_height', models.IntegerField()),
                ('excess', models.CharField(max_length=66)),
                ('excess_sig', models.CharField(max_length=142)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.block')),
            ],
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(db_index=True, max_length=66)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blockchain.block')),
            ],
        ),
    ]
